# These are supported funding model platforms

github: [fozlerabbit] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: fozlerabbi # Replace with a single Patreon username
open_collective: fozlerabbi # Replace with a single Open Collective username
ko_fi: fozlerabbi # Replace with a single Ko-fi username
tidelift: fozlerabbi # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: fozlerabbi # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: fozlerabbi # Replace with a single Liberapay username
issuehunt: fozlerabbi # Replace with a single IssueHunt username
lfx_crowdfunding: fozlerabbi # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
polar: fozlerabbi # Replace with a single Polar username
buy_me_a_coffee: fozlerabbi # Replace with a single Buy Me a Coffee username
thanks_dev: fozlerabbi # Replace with a single thanks.dev username
custom: ['www.buymeacha.com/fozlerabbi'] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
